// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFkllk_I_mwk_-d7kzIYPW-_N3iqALHYo',
    appId: '1:792803924547:web:1d8609060dcf83ab1912f6',
    messagingSenderId: '792803924547',
    projectId: 'chatapptute-8ec65',
    authDomain: 'chatapptute-8ec65.firebaseapp.com',
    storageBucket: 'chatapptute-8ec65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOsx7MtV8-Lg15F85FVnzKi66fk4MSSJE',
    appId: '1:792803924547:android:a8e3850668c645a81912f6',
    messagingSenderId: '792803924547',
    projectId: 'chatapptute-8ec65',
    storageBucket: 'chatapptute-8ec65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDJgzWuLp03mi2OyEs_jO0ENnnxaS10Ik',
    appId: '1:792803924547:ios:6c10d4a3c4902f241912f6',
    messagingSenderId: '792803924547',
    projectId: 'chatapptute-8ec65',
    storageBucket: 'chatapptute-8ec65.firebasestorage.app',
    iosBundleId: 'com.example.chatapptute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDJgzWuLp03mi2OyEs_jO0ENnnxaS10Ik',
    appId: '1:792803924547:ios:6c10d4a3c4902f241912f6',
    messagingSenderId: '792803924547',
    projectId: 'chatapptute-8ec65',
    storageBucket: 'chatapptute-8ec65.firebasestorage.app',
    iosBundleId: 'com.example.chatapptute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFkllk_I_mwk_-d7kzIYPW-_N3iqALHYo',
    appId: '1:792803924547:web:fbc9e5bfaa8fd5661912f6',
    messagingSenderId: '792803924547',
    projectId: 'chatapptute-8ec65',
    authDomain: 'chatapptute-8ec65.firebaseapp.com',
    storageBucket: 'chatapptute-8ec65.firebasestorage.app',
  );
}
